experiment: test-dataset

test-dataset:
  _target_: src.dataset.TestDataset
  n_sample: 256
  random_state: 5

normal-normal:
  _target_: src.dataset.NormalNormalDataset
  n_sample: 256
  n_obs: 10
  random_state: 5
  shrinkage: 1.
  noise: 1.
  dimension: 1

bayes-linreg:
  _target_: src.dataset.BayesLinRegDataset
  n_obs: 10
  n_sample: 256
  random_state: 5
  shrinkage: 1.
  noise: 1.
  dimension: 1


crkp:
  path: "Volumes/umms-esnitkin/Project_KPC_LTACH/Analysis/LTACH_transmission_modeling/data"

train:
  train_frac: 0.7
  batch_size: 64
  # random seed for train-validation split
  seed: 29
  max_epochs: 5
  log_freq: 4

model:
  _target_: src.model.GaussianDensityNetwork
  d_model: 40
  lr: 0.0001
  dropout: 0.0

hydra:
  job:
    chdir: True