experiment: si-model

simulator: &simulator
  n_sample: 256
  random_state: 5


test-dataset:
  _target_: src.dataset.TestDataset
  <<: *simulator

normal-normal:
  _target_: src.dataset.NormalNormalDataset
  <<: *simulator
  n_obs: 10
  shrinkage: 1.
  noise: 1.
  dimension: 1

bayes-linreg:
  _target_: src.dataset.BayesLinRegDataset
  <<: *simulator
  n_obs: 10
  shrinkage: 1.
  noise: 1.
  dimension: 1

si-model:
  _target_: src.dataset.SIModel
  <<: *simulator
  alpha: 0.1 #baseline proportion infected 
  gamma: 0.05 # discharge rate
  beta_true: 0.15 # true infection rate
  prior_mu: -2
  prior_sigma: 0.5
  n_zones: 1
  N: 100 # num patients
  T: 52 # num timesteps



crkp:
  path: "Volumes/umms-esnitkin/Project_KPC_LTACH/Analysis/LTACH_transmission_modeling/data"

train:
  train_frac: 0.7
  batch_size: 64
  # random seed for train-validation split
  seed: 29
  max_epochs: 5
  log_freq: 4

model:
  _target_: src.model.GaussianDensityNetwork
  d_model: 40
  lr: 0.0001
  dropout: 0.0

hydra:
  job:
    chdir: True