experiment: si-model-het

simulator: &simulator
  n_sample: 1000
  observed_seed: 5


test-dataset:
  _target_: src.dataset.TestDataset
  <<: *simulator

normal-normal:
  _target_: src.dataset.NormalNormalDataset
  <<: *simulator
  n_obs: 10
  shrinkage: 1.
  noise: 1.
  dimension: 1

bayes-linreg:
  _target_: src.dataset.BayesLinRegDataset
  <<: *simulator
  n_obs: 10
  shrinkage: 1.
  noise: 1.
  dimension: 1

si-model: &si-model
  _target_: src.dataset.SIModel
  <<: *simulator
  alpha: 0.1 #baseline proportion infected 
  gamma: 0.05 # discharge rate
  beta_true: 0.15 # true infection rate
  prior_mu: -3
  prior_sigma: 1
  N: 100 # num patients
  T: 52 # num timesteps
  summarize: False
  observed_seed: 29
  heterogeneous: False
  pi:
  eta:

si-model-het: &si-model-het
  <<: *si-model
  beta_true: [.05, .02, .04, .06, .08, .1, .05]
  prior_mu: [-3, -3, -3, -3, -3, -3, -3]
  prior_sigma: [1, 1, 1, 1, 1, 1, 1]
  heterogeneous: True
  observed_seed: 31
  N: 300
  gamma: 0.05

si-model-id:
  <<: *si-model
  beta_true: [0.15, 1e-8, 1e-8, 1e-8, 1e-8, 1e-8, 1e-8]
  prior_mu: [-4, -4, -4, -4, -4, -4, -4] # [-3, -1.5, -1.5, -1.5, -1.5, -1.5, 1]
  prior_sigma: [1, 1, 1, 1, 1, 1, 1] # [2, 2, 2, 2, 2, 2, 2]
  heterogeneous: True

si-model-partial:
  <<: *si-model-het # change this to het eventually
  eta: 0.1
  gamma: 0.02

crkp: &crkp
  <<: *simulator
  _target_: src.dataset.crkp.CRKPTransmissionSimulator
  path: /Volumes/umms-esnitkin/Project_KPC_LTACH/Analysis/LTACH_transmission_modeling/preprocessed/resampled
  prior_mu: -1
  prior_sigma: 1
  heterogeneous: False
  N: -1
  pi: None

crkp-het: # best run: d_model = 40
  <<: *crkp
  heterogeneous: true
  prior_mu: [0, 0, 0, 0, 0, 0, 0]
  prior_sigma: [1, 1, 1, 1, 1, 1, 1]
  flatten: True

train:
  train_frac: 0.75
  batch_size:
  # random seed for train-validation split
  seed: 11
  max_epochs: 500
  log_freq: 4
  patience: 10
  stop_early: True
  devices: auto

model:
  _target_: src.model.GaussianDensityNetwork
  d_model: 32
  lr: 0.001
  dropout: 0.0
  weight_decay: 0.0
  mean_field: False

hydra:
  job:
    chdir: True