_target_: src.dataset.crkp.CRKPTransmissionSimulator
path: /Volumes/umms-esnitkin/Project_KPC_LTACH/Analysis/LTACH_transmission_modeling/preprocessed/resampled
prior_mu: -2
prior_sigma: 1
heterogeneous: False
N: -1
pi: