defaults:
  - si-model

beta_true: [.05, .02, .04, .06, .08, .1, .05]
prior_mu: -3
prior_sigma: 1
heterogeneous: True
observed_seed: 31
N: 300
gamma: 0.05
log_scale: True
name: si-model-het
summarize: True
transformer: False
load_data: True